apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: orders-cdc-connector
  labels:
    strimzi.io/cluster: debezium-cdc-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: demodbzmysql.mysql.database.azure.com
    database.port: 3306
    database.user: ${file:/opt/kafka/external-configuration/connector-config/mysql-secret.properties:mysql_username}
    database.password: ${file:/opt/kafka/external-configuration/connector-config/mysql-secret.properties:mysql_password}
    database.ssl.mode: required
    database.server.id: 184054
    database.server.name: demodbzmysql
    database.include.list: demo_debezium_cdc_db
    database.history.kafka.bootstrap.servers: cdc-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: schema-changes.demo_debezium_cdc_db
    include.schema.changes: true 
