apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: pedidos-cdc-connector
  labels:
    strimzi.io/cluster: debezium-cdc-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: <your-mysql-server-name>.mysql.database.azure.com
    database.port: 3306
    database.user: ${file:/opt/kafka/external-configuration/connector-config/mysql-secret.properties:mysql_username}
    database.password: ${file:/opt/kafka/external-configuration/connector-config/mysql-secret.properties:mysql_password}
    database.ssl.mode: required
    database.server.id: 184054
    database.server.name: <your-mysql-server-name>
    database.include.list: tdc_connections_2021_cdc
    database.history.kafka.bootstrap.servers: kafka-cdc-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: schema-changes.tdc_connections_2021_cdc
    include.schema.changes: true 